baseAdminPort   =   9001
plainAdminPort  =  19001
SSLAdminPort    =  29001
baseMServerPort =   9002
plainMServerPort=  19002
adminMServerPort=   9012
serversHostname = 'myhostname'
managedName     = 'myManagedName'
keystorePass    = 'myPass'
privatekeyPass  = 'myPass'
keystoreFile    = '/my/file/to/keystore/location/myManagedName_keystore.jks'
userConfigFilePath='/weblogic/bin/WLSTSecureConfigFile'
userKeyFilePath='/weblogic/bin/WLSTSecureKeyFile'
adminURL='t3s://...:7001'
